package com.nutriai.app.presentation.meals

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.nutriai.app.utils.Resource
import com.nutriai.app.data.remote.ApiService
import com.nutriai.app.di.NetworkModule
import kotlinx.coroutines.flow.first
import com.nutriai.app.data.local.DataStoreManager
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch

class MealPlanningViewModel : ViewModel() {
    
    private val _mealPlansState = MutableStateFlow<Resource<List<MealPlan>>>(Resource.Loading())
    val mealPlansState: StateFlow<Resource<List<MealPlan>>> = _mealPlansState
    
    init {
        loadMealPlans()
    }
    
    private lateinit var apiService: ApiService
    private val dataStoreManager = DataStoreManager()

    private fun ensureApi(context: android.content.Context) {
        if (!::apiService.isInitialized) {
            apiService = NetworkModule.getApiService(context)
        }
    }

    private fun loadMealPlans() {
        viewModelScope.launch {
            try {
                _mealPlansState.value = Resource.Loading()
                
                // For now, return mock data
                // In the future, this will call the repository
                val mockMealPlans = listOf(
                    MealPlan(
                        id = "1",
                        name = "Balanced Weekly Plan",
                        description = "A balanced meal plan for the entire week",
                        days = listOf(
                            MealPlanDay(
                                day = "Monday",
                                meals = listOf(
                                    MealPlanMeal(
                                        type = "breakfast",
                                        name = "Oatmeal with Berries",
                                        calories = 320,
                                        protein = 12,
                                        carbs = 45,
                                        fat = 12,
                                        ingredients = listOf("Oats", "Berries", "Honey", "Nuts"),
                                        instructions = "Cook oats with water, top with berries and nuts"
                                    )
                                )
                            )
                        ),
                        totalCalories = 2000,
                        totalProtein = 120,
                        totalCarbs = 250,
                        totalFat = 65,
                        createdAt = "2024-01-15"
                    )
                )
                
                _mealPlansState.value = Resource.Success(mockMealPlans)
                
            } catch (e: Exception) {
                android.util.Log.e("MealPlanningViewModel", "❌ Error loading meal plans: ${e.message}", e)
                _mealPlansState.value = Resource.Error("Failed to load meal plans: ${e.message}")
            }
        }
    }
    
    fun generateAIRecommendedMealPlan(context: android.content.Context? = null) {
        viewModelScope.launch {
            try {
                android.util.Log.d("MealPlanningViewModel", "🤖 Generating AI recommended meal plan...")
                context?.let { ensureApi(it) }
                val token = dataStoreManager.authToken.first()
                if (::apiService.isInitialized && token != null) {
                    val body = mapOf(
                        "weekStart" to java.time.LocalDate.now().toString(),
                        "preferences" to mapOf(
                            "dietaryRestrictions" to emptyList<String>(),
                            "cookingTime" to "medium",
                            "servings" to 1,
                            "budget" to "medium"
                        )
                    )
                    val res = apiService.generateMealPlan("Bearer $token", body)
                    if (res.isSuccessful) {
                        // Convert server mealPlan to local model list (simple wrapper)
                        _mealPlansState.value = Resource.Success(
                            listOf(
                                MealPlan(
                                    id = System.currentTimeMillis().toString(),
                                    name = "AI Weekly Plan",
                                    description = "Generated by AI",
                                    days = emptyList(),
                                    totalCalories = 0,
                                    totalProtein = 0,
                                    totalCarbs = 0,
                                    totalFat = 0,
                                    createdAt = java.time.LocalDate.now().toString()
                                )
                            )
                        )
                        return@launch
                    }
                }
                // Fallback to mock
                loadMealPlans()
                
            } catch (e: Exception) {
                android.util.Log.e("MealPlanningViewModel", "❌ Error generating meal plan: ${e.message}", e)
                _mealPlansState.value = Resource.Error("Failed to generate meal plan: ${e.message}")
            }
        }
    }
    
    fun createMealPlan(name: String, description: String, context: android.content.Context? = null) {
        viewModelScope.launch {
            try {
                android.util.Log.d("MealPlanningViewModel", "📝 Creating new meal plan: $name")
                context?.let { ensureApi(it) }
                val token = dataStoreManager.authToken.first()
                if (::apiService.isInitialized && token != null) {
                    val body = mapOf(
                        "name" to name,
                        "mealPlan" to mapOf("days" to emptyList<Any>())
                    )
                    apiService.saveMealPlan("Bearer $token", body)
                }
                loadMealPlans()
                
            } catch (e: Exception) {
                android.util.Log.e("MealPlanningViewModel", "❌ Error creating meal plan: ${e.message}", e)
                _mealPlansState.value = Resource.Error("Failed to create meal plan: ${e.message}")
            }
        }
    }
}
